references:
    basepath: "path_to_references_data"
    provider: "ucsc"
    release: "hg19"
genome_fasta: "ucsc.hg19.fasta"
genes_gtf: "Annotation/Genes/genes.gtf"
tx2gene_hsa: "rna/tx2gene_hsa.RData"

rseqc_reference:
    basepath: "path_to_references_data"
    provider: "rseqc"
    release: "hg19"
housekeeping: "hg19.HouseKeepingGenes.bed"
refseq: "hg19_RefSeq.bed"

transcriptome_reference:
    basepath: "path_to_references_data"
    provider: "ensembl"
    release: "GRCh38"
transcriptome_fasta: "Homo_sapiens.GRCh38.cdna.all.fa.gz"

bbduk_reference:
    bbduk_se:"Path to rRNA fasta file"
    bbduk_pe:"Path to rRNA fasta file"
		       
strand: "reverse"

rules:
    sleuth_run:
        database: "ensembl"
        dataset: "hsapiens_gene_ensembl"
        version: 90
    multiqc:
        arguments: "--force "
    featureCounts_run:
        gtf_feature_type: "exon"
        gtf_attribute_type: "gene_id"
    kallisto:
        arguments_pe: ""
        arguments_se: "--single -b 30 -l 280 -s 80 "
    trim_galore_pe:
        arguments: "-q 20"
    trim_galore_se:
        arguments: "-q 20"
    fastq_screen:
        params: "--force --aligner bowtie2 --subset 100000 --nohits"
        config_file: "../data/fastq_screen.config"
wrappers:
    fastqc: "fastqc_wrapper"
    trim_galore_se: "trim_galore_se_wrapper"
    trim_galore_pe: "trim_galore_pe_wrapper"

samples: samples.tsv
units: units.tsv
reheader: reheader.tsv
internal_sid: "LIMS"
read_type: "pe"