references:
    basepath: "path_to_references_data"
    provider: "ucsc"
    release: "hg19"
genome_fasta: "ucsc.hg19.fasta"
genes_gtf: "Annotation/Genes/genes.gtf"

rseqc_reference:
    basepath: "path_to_references_data"
    provider: "rseqc"
    release: "hg19"
housekeeping: "hg19.HouseKeepingGenes.bed"
refseq: "hg19_RefSeq.bed"

transcriptome_reference:
    basepath: "path_to_references_data"
    provider: "ensembl"
    release: "GRCh38"
transcriptome_fasta: "Homo_sapiens.GRCh38.cdna.all.fa.gz"

strand: "reverse"

rules:
    sleuth_run:
        database: "ensembl"
        dataset: "hsapiens_gene_ensembl"
        version: 90
    multiqc:
        arguments: "--force "
    featureCounts_run:
        gtf_feature_type: "exon"
        gtf_attribute_type: "gene_id"
    kallisto:
        arguments: ""
    trim_galore_pe:
        arguments: "-q 20"
    fastq_screen:
        params: "--force --aligner bowtie2 --subset 100000 --nohits"
        config_file: "../data/fastq_screen.config"

wrappers:
    fastqc: "fastqc_wrapper"
    trim_galore: "trim_galore_se_wrapper"

samples: samples.tsv